### ISSUE TITLE
Unable to display new tab properly

### ISSUE THREAD

**Issue by liby** [dukeluo/wai#105]
<img width="2160" alt="image" src="https://github.com/dukeluo/wai/assets/38807139/1df3ec5a-3fa2-4f4a-99e3-cc90caaee099">

<img width="494" alt="image" src="https://github.com/dukeluo/wai/assets/38807139/292b35e0-1c42-4995-917e-7523c6cda907">

Chrome Version 122.0.6261.94 (Official Build) (x86_64)

**Comment by dukeluo** [comment]
Hi everyone. Im so sorry for this bug. Today is February 29th, a special day, but the built-in Wikipedia data does not contain today's data, so it will get a null, which causes this bug. I think this issue will be fixed automatically tomorrow, and I'll also release a hotfix containing today's Wikipedia data to avoid having this issue four years from now.

**Comment by dukeluo** [comment]
v1.4.2 has been released.
