### ISSUE TITLE
这项目我吹爆了

### ISSUE THREAD

**Issue by LiuN1an** [DukeLuo/wai#46]
话说为啥不直接对 body 进行 transform，元素分开 transform 的有啥隐藏福利么？

**Comment by DukeLuo** [comment]
为了防止偷懒，无论哪个角度你都需要扭动脖子

**Comment by DukeLuo** [comment]
非 bug 类 issue 先关闭啦，欢迎移步[隔壁讨论区](https://github.com/DukeLuo/wai/discussions)聊天吹水
