### ISSUE TITLE
分辨率适配

### ISSUE THREAD

**Issue by BLU1998** [DukeLuo/wai#47]
当使用网页版的歪脖子时，网页过长，需要上下滑动，就差那么一丢丢（隐藏书签栏后也不行），有点强迫症。谢谢。
浏览器是chrome最新版，屏幕是1080p的。
![image](https://user-images.githubusercontent.com/24390554/181914524-649fb308-4924-4449-b583-377410c5f0fa.png)

**Comment by DukeLuo** [comment]
@BLU1998 ，谢谢反馈，请问是 Windows 还是 Mac ？

**Comment by BLU1998** [comment]
系统是win 11。麻烦了😊

**Comment by DukeLuo** [comment]
我在 win10 上测试了下，表现挺好的，请问访问在线体验站 [https://wai.shaiwang.life/](https://wai.shaiwang.life/) 也是一样的问题吗

**Comment by BLU1998** [comment]
https://wai.shaiwang.life/ 这个的使用没有问题。我之前访问的是https://wai.shaiwang.life/?utm_source=appinn.com
谢谢，我以后使用前面那个网址就可以了。

**Comment by DukeLuo** [comment]
那个地址并不是我分发的，请以官网体验站 [ https://wai.shaiwang.life/ ]( https://wai.shaiwang.life/ ) 为准。

**Comment by DukeLuo** [comment]
没有问题的话，我先关闭这个 issue 了，有问题再联系～

**Comment by BLU1998** [comment]
谢谢
