### ISSUE TITLE
公式加载问题

### ISSUE THREAD

**Issue by wuyudi** [DukeLuo/wai#69]
![image](https://user-images.githubusercontent.com/30024051/194028943-3b7041c6-4bc6-4cc5-b1f8-973245c3ddff.png)

看了 wiki 原文

https://zh.m.wikipedia.org/zh-hk/10%E6%9C%885%E6%97%A5

![image](https://user-images.githubusercontent.com/30024051/194029742-2712ae7b-eb8a-428c-81dc-6a4e60cb166e.png)

应该是处理文本时没有解决公式问题。

**Comment by DukeLuo** [comment]
谢谢 issue，确实是爬取数据时没对公式特殊处理而出现的问题。爬取的数据中只有这一条是这样的，先手动删除了。

**Comment by DukeLuo** [comment]
已把坏数据给移除，扩展新版本 1.1.0 已提审，在线体验站已修复。

**Comment by DukeLuo** [comment]
新版本已上架
