### ISSUE TITLE
[feature request] 火狐插件让主页也能使用歪脖

### ISSUE THREAD

**Issue by rainbowflesh** [DukeLuo/wai#72]
![img](https://i.imgur.com/cULgu1R.png)
同时启用了两个插件, 想让主页显示歪脖, 新建标签显示另一个😎

**Comment by DukeLuo** [comment]
我看到火狐支持把网站设置为主页，你可试试把主页设置为歪脖子的网页版 [https://wai.shaiwang.life/](https://wai.shaiwang.life/)
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/26000789/213687065-d7d40575-7524-4e32-b977-ab3e60766f1d.png">
