### ISSUE TITLE
希望能结合摸鱼人日历

### ISSUE THREAD

**Issue by gyf9835** [DukeLuo/wai#78]
打工人必备：摸鱼+预防颈椎病
摸鱼人日历API：[https://api.vvhan.com/moyu.html](https://api.vvhan.com/moyu.html)

或者支持自定义api，让用户个性化定义页面内容

**Comment by DukeLuo** [comment]
谢谢建议。我看了一下摸鱼日历 API，它返回一张日历图片，我还没想到在保持风格下集成它🧐
