### ISSUE TITLE
怎么突然不歪了？

### ISSUE THREAD

**Issue by moccanism** [dukeluo/wai#96]
某一天突然不歪了，一直都是正的。。。刚才升级到1.4.0也没有解决

MacOS 13.4.1
Chrome 版本 116.0.5845.96（正式版本） (x86_64)

![WX20230823-211633@2x](https://github.com/dukeluo/wai/assets/24928504/974a3e3b-9e1b-48a5-af28-68234f9e8344)

**Comment by dukeluo** [comment]
@moccanism 你 mac 是什么版本呢，屏幕特别小吗？最新版中新加的逻辑，屏宽或者屏高小于 820 px，就不会歪了。

**Comment by Sansui233** [comment]
我这边也是不歪了，刷新后也没有随机，2k屏，全屏显示

**Comment by dukeluo** [comment]
@Sansui233 能提供下屏幕屏幕大小信息吗，我估计是屏高少于 820 px 引起的

**Comment by Sansui233** [comment]
看了一下，好像和系统缩放有关系。2k的分辨率高1600，在无缩放的情况下chrome窗口大小最高为1100，在150%缩放的情况下最高就是710左右。但现在HiDPI的屏幕使用100%无缩放字很小，我电脑的推荐缩放就是150%。之前用的 Mac 的 Retina 13.3 基本调成显示为720p，不过由于四倍像素密度很清楚。Chrome也还是不足800。

**Comment by moccanism** [comment]
> @moccanism 你 mac 是哪款呢，屏幕特别小吗？最新版中新加的逻辑，屏宽或者屏高小于 820 px，就不会歪了。

Mbp 13-inch, 2020, Four Thunderbolt 3 ports

**Comment by dukeluo** [comment]
@moccanism @Sansui233 我移除了高度限制，部署了一版到[网页在线版](https://wai.shaiwang.life/)，能帮忙看看效果吗

**Comment by Sansui233** [comment]
> @moccanism @Sansui233 我移除了高度限制，部署了一版到[网页在线版](https://wai.shaiwang.life/)，能帮忙看看效果吗

这样的，好像四周留白更多，信息量比之前少，然后部分旋转角度会出现文字和时间的重叠。话说限高之前的是有什么问题吗
<img width="935" alt="屏幕截图 2023-08-27 195659" src="https://github.com/dukeluo/wai/assets/27474981/c481d01c-2b82-4864-8378-97ce17edae3e">

**Comment by dukeluo** [comment]
@Sansui233 多谢反馈，时间信息区域字号有些大，把内容都挤到一起了；以前做法是想着对小屏幕好一些。
能打开浏览器控制台，看看你的这三个属性的值吗？
- `window.screen.width`
- `window.screen.height`
-  `window.devicePixelRatio ` 
<img width="484" alt="image" src="https://github.com/dukeluo/wai/assets/26000789/2a6c3892-d351-4eda-bdf0-c17f1f14eada">

**Comment by Sansui233** [comment]
@dukeluo 
```
window.screen.width
1377
window.screen.height
861
window.devicePixelRatio 
1.8600000143051147
```

**Comment by flyfire** [comment]
window.screen.width
1536
window.screen.height
864
window.devicePixelRatio
1.25

Windows 11上也是不歪的

**Comment by dukeluo** [comment]
@Sansui233 @flyfire 我又修改了一版，部署到[网页在线版](https://wai.shaiwang.life/)，能帮忙看看现在的效果吗

**Comment by yang1c** [comment]
![image](https://github.com/dukeluo/wai/assets/65067873/d5bb5cd7-8696-4755-a16c-c1ba6ec27cd0)
还以为是设置问题，确实不是正的，就是全部颠倒

**Comment by yang1c** [comment]
> 

![image](https://github.com/dukeluo/wai/assets/65067873/cc5de58c-f685-4836-b7ee-83a663d32b2a)
字重叠了，怪不得突然感觉太正了，原来是有bug

**Comment by dukeluo** [comment]
@yang1c 谢谢你的回复，应该是高清屏太窄没适配好引起的。我想确认下你截图的是 https://wai.shaiwang.life/ 吗？另外可以打开控制台，并把控制台放置在右侧（因为放在底部会影响 `innerHeight` 值），能看看你这几个属性的值吗？
```
window.screen.width
window.screen.height
window.innerHeight 
window.devicePixelRatio 
```
<img width="1517" alt="image" src="https://github.com/dukeluo/wai/assets/26000789/a3ed254b-2c43-4edc-8abc-e5e3ffe4e298">

**Comment by moccanism** [comment]
我这里是这样
<img width="1299" alt="image" src="https://github.com/dukeluo/wai/assets/24928504/a4614147-8831-4007-8015-190685e35fc7">

**Comment by dukeluo** [comment]
@moccanism 多谢，效果看着还行，没有挤换行了

**Comment by dukeluo** [comment]
已提交 1.4.1 版本，包含针对这个问题的修改。

**Comment by xchrix** [comment]
![图片](https://github.com/dukeluo/wai/assets/26772408/267b9b4f-648b-42fc-b8ea-e49a3dfda74b)
现在可以旋转了，但是不同部分之间有一些遮挡。右下角的按钮有点太大了
```
window.screen.width
1184
window.screen.height
666
window.innerHeight
551
window.devicePixelRatio
1.6216216216216217 
```

**Comment by moccanism** [comment]
@dukeluo 27寸4K 满屏(非mac全屏模式)，浏览器直接缩放会出现重叠，但是同比例下直接刷新一下页面就不重叠了。这次修改就是字有点小，其余的挺好

**Comment by dukeluo** [comment]
@moccanism 
> 测试了一下，无论窗口大小，浏览器直接缩放到不同比例下都会有重叠这种现象，但是同比例下直接刷新一下页面就不重叠了。

这是因为先要知道视图窗口的信息才能布局，现在视图窗口发生了变化，还不会自动重新布局，需要手动刷新一下，未来会修 :)
